name: Build human-friendly metadata index

on:
  push:
    branches: [main]
    paths:
      - "metadata/*.json"
      - "samples/*.wav"
      - ".github/workflows/build-index.yml"   # odpali się też po zmianie workflow
  workflow_dispatch:                           # przycisk "Run workflow" w UI

permissions:
  contents: write

jobs:
  build-index:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Generate metadata/index.md
        run: |
          set -euo pipefail
          human_size () {
            b=$1
            if [ "$b" -lt 1024 ]; then echo "${b} B"; exit 0; fi
            awk -v b="$b" 'function human(x){ s="BKMGTPE"; while (x>=1024){x/=1024; s=substr(s,2)}; return sprintf("%.1f %s", x, substr(s,1,1)) } BEGIN{print human(b)}'
          }
          echo "# 📑 Indeks nagrań i metadanych" > metadata/index.md
          echo "" >> metadata/index.md
          echo "Lista nagrań z linkami do **audio (.wav)** i **metadanych (.json)**." >> metadata/index.md
          echo "" >> metadata/index.md
          echo "| ID próbki | Model | Data | Audio | Rozmiar | Metadane |" >> metadata/index.md
          echo "|---|---|---|---|---:|---|" >> metadata/index.md
          shopt -s nullglob
          for wav in samples/*.wav; do
            base=$(basename "$wav" .wav)
            json="metadata/${base}.json"
            bytes=$(stat -c%s "$wav" 2>/dev/null || stat -f%z "$wav"); size=$(human_size "$bytes")
            if [ -f "$json" ]; then
              model=$(jq -r '.drone_model // empty' "$json" 2>/dev/null || echo "")
              date=$(jq -r '.added_at // empty' "$json" 2>/dev/null || echo "")
            else model=""; date=""; fi
            [ -z "$model" ] && model="—"; [ -z "$date" ] && date="—"
            audio_link="[${base}.wav](../samples/${base}.wav)"
            meta_link=$([ -f "$json" ] && echo "[${base}.json](${base}.json)" || echo "—")
            echo "| \`${base}\` | ${model} | ${date} | ${audio_link} | ${size} | ${meta_link} |" >> metadata/index.md
          done

      - name: Commit changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add metadata/index.md
          git commit -m "Update metadata index" || echo "No changes to commit"
          git push
