name: Deploy data page (separate from repo tree)

on:
  push:
    branches: [main]
    paths:
      - "metadata/index.md"
      - "metadata/*.json"
      - "samples/*.wav"
      - ".github/workflows/pages.yml"
  workflow_dispatch: {}

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build site/
        run: |
          set -euo pipefail
          rm -rf site
          mkdir -p site/data site/samples
          # przenieś indeks jako stronę /data/
          cp metadata/index.md site/data/index.md
          # skopiuj pliki, żeby linki działały też na Pages
          cp -r metadata/*.json site/data/ || true
          cp -r samples/*.wav site/samples/ || true
          # wyłącz Jekylla (serwuj .json/.wav 1:1)
          touch site/.nojekyll

      - uses: actions/upload-pages-artifact@v3
        with:
          path: site

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
